In [1]:
import numpy as np
import pandas as pd

In [2]:
#reading the dataset
df=pd.read_csv("Tweets.csv")

In [9]:
df.head()

tweet_id airline_sentiment  airline_sentiment_confidence  \
0  570306133677760513           neutral                        1.0000   
1  570301130888122368          positive                        0.3486   
2  570301083672813571           neutral                        0.6837   
3  570301031407624196          negative                        1.0000   
4  570300817074462722          negative                        1.0000   

  negativereason  negativereason_confidence         airline  \
0            NaN                        NaN  Virgin America   
1            NaN                     0.0000  Virgin America   
2            NaN                        NaN  Virgin America   
3     Bad Flight                     0.7033  Virgin America   
4     Can't Tell                     1.0000  Virgin America   

  airline_sentiment_gold        name negativereason_gold  retweet_count  \
0                    NaN     cairdin                 NaN              0   
1                    NaN    jnardino                 NaN              0   
2                    NaN  yvonnalynn                 NaN              0   
3                    NaN    jnardino                 NaN              0   
4                    NaN    jnardino                 NaN              0   

                                                text tweet_coord  \
0                @VirginAmerica What @dhepburn said.         NaN   
1  @VirginAmerica plus you've added commercials t...         NaN   
2  @VirginAmerica I didn't today... Must mean I n...         NaN   
3  @VirginAmerica it's really aggressive to blast...         NaN   
4  @VirginAmerica and it's a really big bad thing...         NaN   

               tweet_created tweet_location               user_timezone  
0  2015-02-24 11:35:52 -0800            NaN  Eastern Time (US & Canada)  
1  2015-02-24 11:15:59 -0800            NaN  Pacific Time (US & Canada)  
2  2015-02-24 11:15:48 -0800      Lets Play  Central Time (US & Canada)  
3  2015-02-24 11:15:36 -0800            NaN  Pacific Time (US & Canada)  
4  2015-02-24 11:14:45 -0800            NaN  Pacific Time (US & Canada)

In [10]:
import nltk

In [11]:
nltk.download("punkt")
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt to C:\Users\Tejal
[nltk_data]     V\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to C:\Users\Tejal
[nltk_data]     V\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.


True

In [12]:
from nltk.tokenize import word_tokenize

In [13]:
df.tail()

tweet_id airline_sentiment  airline_sentiment_confidence  \
14635  569587686496825344          positive                        0.3487   
14636  569587371693355008          negative                        1.0000   
14637  569587242672398336           neutral                        1.0000   
14638  569587188687634433          negative                        1.0000   
14639  569587140490866689           neutral                        0.6771   

               negativereason  negativereason_confidence   airline  \
14635                     NaN                     0.0000  American   
14636  Customer Service Issue                     1.0000  American   
14637                     NaN                        NaN  American   
14638  Customer Service Issue                     0.6659  American   
14639                     NaN                     0.0000  American   

      airline_sentiment_gold             name negativereason_gold  \
14635                    NaN  KristenReenders                 NaN   
14636                    NaN         itsropes                 NaN   
14637                    NaN         sanyabun                 NaN   
14638                    NaN       SraJackson                 NaN   
14639                    NaN        daviddtwu                 NaN   

       retweet_count                                               text  \
14635              0  @AmericanAir thank you we got on a different f...   
14636              0  @AmericanAir leaving over 20 minutes Late Flig...   
14637              0  @AmericanAir Please bring American Airlines to...   
14638              0  @AmericanAir you have my money, you change my ...   
14639              0  @AmericanAir we have 8 ppl so we need 2 know h...   

      tweet_coord              tweet_created tweet_location  \
14635         NaN  2015-02-22 12:01:01 -0800            NaN   
14636         NaN  2015-02-22 11:59:46 -0800          Texas   
14637         NaN  2015-02-22 11:59:15 -0800  Nigeria,lagos   
14638         NaN  2015-02-22 11:59:02 -0800     New Jersey   
14639         NaN  2015-02-22 11:58:51 -0800     dallas, TX   

                    user_timezone  
14635                         NaN  
14636                         NaN  
14637                         NaN  
14638  Eastern Time (US & Canada)  
14639                         NaN

In [14]:
x=df.iloc[0,1]
x

'neutral'

In [15]:
import re

In [3]:
df.dropna(subset=["text", "airline_sentiment"], inplace=True)


In [7]:
df["text"] = df["text"].astype(str)
df["airline_sentiment"] = df["airline_sentiment"].astype(str)
df["airline"] = df["airline"].astype(str)
df["negativereason"] = df["negativereason"].astype(str)  # Optional if needed


In [5]:
df.to_csv("Tweets.csv", index=False)


In [8]:
df

tweet_id airline_sentiment  airline_sentiment_confidence  \
0      570306133677760513           neutral                        1.0000   
1      570301130888122368          positive                        0.3486   
2      570301083672813571           neutral                        0.6837   
3      570301031407624196          negative                        1.0000   
4      570300817074462722          negative                        1.0000   
...                   ...               ...                           ...   
14635  569587686496825344          positive                        0.3487   
14636  569587371693355008          negative                        1.0000   
14637  569587242672398336           neutral                        1.0000   
14638  569587188687634433          negative                        1.0000   
14639  569587140490866689           neutral                        0.6771   

               negativereason  negativereason_confidence         airline  \
0                         nan                        NaN  Virgin America   
1                         nan                     0.0000  Virgin America   
2                         nan                        NaN  Virgin America   
3                  Bad Flight                     0.7033  Virgin America   
4                  Can't Tell                     1.0000  Virgin America   
...                       ...                        ...             ...   
14635                     nan                     0.0000        American   
14636  Customer Service Issue                     1.0000        American   
14637                     nan                        NaN        American   
14638  Customer Service Issue                     0.6659        American   
14639                     nan                     0.0000        American   

      airline_sentiment_gold             name negativereason_gold  \
0                        NaN          cairdin                 NaN   
1                        NaN         jnardino                 NaN   
2                        NaN       yvonnalynn                 NaN   
3                        NaN         jnardino                 NaN   
4                        NaN         jnardino                 NaN   
...                      ...              ...                 ...   
14635                    NaN  KristenReenders                 NaN   
14636                    NaN         itsropes                 NaN   
14637                    NaN         sanyabun                 NaN   
14638                    NaN       SraJackson                 NaN   
14639                    NaN        daviddtwu                 NaN   

       retweet_count                                               text  \
0                  0                @VirginAmerica What @dhepburn said.   
1                  0  @VirginAmerica plus you've added commercials t...   
2                  0  @VirginAmerica I didn't today... Must mean I n...   
3                  0  @VirginAmerica it's really aggressive to blast...   
4                  0  @VirginAmerica and it's a really big bad thing...   
...              ...                                                ...   
14635              0  @AmericanAir thank you we got on a different f...   
14636              0  @AmericanAir leaving over 20 minutes Late Flig...   
14637              0  @AmericanAir Please bring American Airlines to...   
14638              0  @AmericanAir you have my money, you change my ...   
14639              0  @AmericanAir we have 8 ppl so we need 2 know h...   

      tweet_coord              tweet_created tweet_location  \
0             NaN  2015-02-24 11:35:52 -0800            NaN   
1             NaN  2015-02-24 11:15:59 -0800            NaN   
2             NaN  2015-02-24 11:15:48 -0800      Lets Play   
3             NaN  2015-02-24 11:15:36 -0800            NaN   
4             NaN  2015-02-24 11:14:45 -0800            NaN   
...           ...                        ...            ...   
14635   

In [9]:
df

tweet_id airline_sentiment  airline_sentiment_confidence  \
0      570306133677760513           neutral                        1.0000   
1      570301130888122368          positive                        0.3486   
2      570301083672813571           neutral                        0.6837   
3      570301031407624196          negative                        1.0000   
4      570300817074462722          negative                        1.0000   
...                   ...               ...                           ...   
14635  569587686496825344          positive                        0.3487   
14636  569587371693355008          negative                        1.0000   
14637  569587242672398336           neutral                        1.0000   
14638  569587188687634433          negative                        1.0000   
14639  569587140490866689           neutral                        0.6771   

               negativereason  negativereason_confidence         airline  \
0                         nan                        NaN  Virgin America   
1                         nan                     0.0000  Virgin America   
2                         nan                        NaN  Virgin America   
3                  Bad Flight                     0.7033  Virgin America   
4                  Can't Tell                     1.0000  Virgin America   
...                       ...                        ...             ...   
14635                     nan                     0.0000        American   
14636  Customer Service Issue                     1.0000        American   
14637                     nan                        NaN        American   
14638  Customer Service Issue                     0.6659        American   
14639                     nan                     0.0000        American   

      airline_sentiment_gold             name negativereason_gold  \
0                        NaN          cairdin                 NaN   
1                        NaN         jnardino                 NaN   
2                        NaN       yvonnalynn                 NaN   
3                        NaN         jnardino                 NaN   
4                        NaN         jnardino                 NaN   
...                      ...              ...                 ...   
14635                    NaN  KristenReenders                 NaN   
14636                    NaN         itsropes                 NaN   
14637                    NaN         sanyabun                 NaN   
14638                    NaN       SraJackson                 NaN   
14639                    NaN        daviddtwu                 NaN   

       retweet_count                                               text  \
0                  0                @VirginAmerica What @dhepburn said.   
1                  0  @VirginAmerica plus you've added commercials t...   
2                  0  @VirginAmerica I didn't today... Must mean I n...   
3                  0  @VirginAmerica it's really aggressive to blast...   
4                  0  @VirginAmerica and it's a really big bad thing...   
...              ...                                                ...   
14635              0  @AmericanAir thank you we got on a different f...   
14636              0  @AmericanAir leaving over 20 minutes Late Flig...   
14637              0  @AmericanAir Please bring American Airlines to...   
14638              0  @AmericanAir you have my money, you change my ...   
14639              0  @AmericanAir we have 8 ppl so we need 2 know h...   

      tweet_coord              tweet_created tweet_location  \
0             NaN  2015-02-24 11:35:52 -0800            NaN   
1             NaN  2015-02-24 11:15:59 -0800            NaN   
2             NaN  2015-02-24 11:15:48 -0800      Lets Play   
3             NaN  2015-02-24 11:15:36 -0800            NaN   
4             NaN  2015-02-24 11:14:45 -0800            NaN   
...           ...                        ...            ...   
14635   

In [10]:
tokens=[word_tokenize(x) for x in df['Text']]

KeyError: 'Text'

In [86]:
tokens[5]

['PGNX', 'Over', '3.04']

In [87]:
#to remove stop words
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\mehna\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [88]:
stop=stopwords.words('english')

In [89]:
stop_token=[]
for x in tokens:
  cl = [i for i in x if i not in stop]
  stop_token.append(cl)

In [90]:
stop_token

[['Kickers',
  'watchlist',
  'XIDE',
  'TIT',
  'SOQ',
  'PNK',
  'CPW',
  'BPZ',
  'AJ',
  'trade',
  'method',
  '1',
  'method',
  '2',
  ',',
  'see',
  'prev',
  'posts'],
 ['user',
  ':',
  'AAP',
  'MOVIE',
  '.',
  '55',
  '%',
  'return',
  'FEA/GEED',
  'indicator',
  '15',
  'trades',
  'year',
  '.',
  'AWESOME',
  '.'],
 ['user',
  'I',
  "'d",
  'afraid',
  'short',
  'AMZN',
  '-',
  'looking',
  'like',
  'near-monopoly',
  'eBooks',
  'infrastructure-as-a-service'],
 ['MNTA', 'Over', '12.00'],
 ['OI', 'Over', '21.37'],
 ['PGNX', 'Over', '3.04'],
 ['AAP',
  '-',
  'user',
  'current',
  'downtrend',
  'break',
  '.',
  'Otherwise',
  'short-term',
  'correction',
  'med-term',
  'downtrend',
  '.'],
 ['Monday',
  "'s",
  'relative',
  'weakness',
  '.',
  'NYX',
  'WIN',
  'TIE',
  'TAP',
  'ICE',
  'INT',
  'BMC',
  'AON',
  'C',
  'CHK',
  'BIIB'],
 ['GOOG',
  '-',
  'ower',
  'trend',
  'line',
  'channel',
  'test',
  '&',
  'volume',
  'support',
  '.'],
 ['AAP', 

In [91]:
from nltk.stem import PorterStemmer
ps=PorterStemmer()

In [92]:
stemedata =[]
for message in stop_token:
  st = [ps.stem(word) for word in message]
  stemedata.append(st)

In [93]:
stemedata

[['kicker',
  'watchlist',
  'xide',
  'tit',
  'soq',
  'pnk',
  'cpw',
  'bpz',
  'aj',
  'trade',
  'method',
  '1',
  'method',
  '2',
  ',',
  'see',
  'prev',
  'post'],
 ['user',
  ':',
  'aap',
  'movi',
  '.',
  '55',
  '%',
  'return',
  'fea/ge',
  'indic',
  '15',
  'trade',
  'year',
  '.',
  'awesom',
  '.'],
 ['user',
  'i',
  "'d",
  'afraid',
  'short',
  'amzn',
  '-',
  'look',
  'like',
  'near-monopoli',
  'ebook',
  'infrastructure-as-a-servic'],
 ['mnta', 'over', '12.00'],
 ['oi', 'over', '21.37'],
 ['pgnx', 'over', '3.04'],
 ['aap',
  '-',
  'user',
  'current',
  'downtrend',
  'break',
  '.',
  'otherwis',
  'short-term',
  'correct',
  'med-term',
  'downtrend',
  '.'],
 ['monday',
  "'s",
  'rel',
  'weak',
  '.',
  'nyx',
  'win',
  'tie',
  'tap',
  'ice',
  'int',
  'bmc',
  'aon',
  'c',
  'chk',
  'biib'],
 ['goog',
  '-',
  'ower',
  'trend',
  'line',
  'channel',
  'test',
  '&',
  'volum',
  'support',
  '.'],
 ['aap', 'watch', 'tomorrow', 'ong', 'e

In [94]:
#apply pos_tagging on data
from nltk.tag import pos_tag
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\mehna\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!


True

In [95]:
pos_token=[pos_tag(message) for message in stop_token]

In [96]:
pos_token

[[('Kickers', 'NNS'),
  ('watchlist', 'VBP'),
  ('XIDE', 'NNP'),
  ('TIT', 'NNP'),
  ('SOQ', 'NNP'),
  ('PNK', 'NNP'),
  ('CPW', 'NNP'),
  ('BPZ', 'NNP'),
  ('AJ', 'NNP'),
  ('trade', 'NN'),
  ('method', 'NN'),
  ('1', 'CD'),
  ('method', 'NN'),
  ('2', 'CD'),
  (',', ','),
  ('see', 'VBP'),
  ('prev', 'JJ'),
  ('posts', 'NNS')],
 [('user', 'NN'),
  (':', ':'),
  ('AAP', 'NNP'),
  ('MOVIE', 'NNP'),
  ('.', '.'),
  ('55', 'CD'),
  ('%', 'NN'),
  ('return', 'NN'),
  ('FEA/GEED', 'NNP'),
  ('indicator', 'NN'),
  ('15', 'CD'),
  ('trades', 'NNS'),
  ('year', 'NN'),
  ('.', '.'),
  ('AWESOME', 'NNP'),
  ('.', '.')],
 [('user', 'NN'),
  ('I', 'PRP'),
  ("'d", 'MD'),
  ('afraid', 'VB'),
  ('short', 'JJ'),
  ('AMZN', 'NNP'),
  ('-', ':'),
  ('looking', 'VBG'),
  ('like', 'IN'),
  ('near-monopoly', 'JJ'),
  ('eBooks', 'NNS'),
  ('infrastructure-as-a-service', 'JJ')],
 [('MNTA', 'NNP'), ('Over', 'NNP'), ('12.00', 'CD')],
 [('OI', 'NNP'), ('Over', 'NNP'), ('21.37', 'CD')],
 [('PGNX', 'NNP'), ('Ov

In [97]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('omw-1.4')
lemmatizer=WordNetLemmatizer()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\mehna\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\mehna\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [98]:
from nltk.corpus import wordnet

def get_wordnet_pos(treebank_tag):
    if treebank_tag.startswith('J'):
        return wordnet.ADJ
    elif treebank_tag.startswith('V'):
        return wordnet.VERB
    elif treebank_tag.startswith('N'):
        return wordnet.NOUN
    elif treebank_tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN  # Default to NOUN if POS tag is unknown


In [99]:
pos_token[0][0]

('Kickers', 'NNS')

In [100]:
get_wordnet_pos(pos_token[0][0][1])

'n'

In [101]:
lem_data = []
for x in range(len(pos_token)):
  lem = [lemmatizer.lemmatize(pos_token[x][i][0],get_wordnet_pos(pos_token[x][i][1])) for i in range(len(pos_token[x]))]
  lem_data.append(lem)

In [102]:
lem_data

[['Kickers',
  'watchlist',
  'XIDE',
  'TIT',
  'SOQ',
  'PNK',
  'CPW',
  'BPZ',
  'AJ',
  'trade',
  'method',
  '1',
  'method',
  '2',
  ',',
  'see',
  'prev',
  'post'],
 ['user',
  ':',
  'AAP',
  'MOVIE',
  '.',
  '55',
  '%',
  'return',
  'FEA/GEED',
  'indicator',
  '15',
  'trade',
  'year',
  '.',
  'AWESOME',
  '.'],
 ['user',
  'I',
  "'d",
  'afraid',
  'short',
  'AMZN',
  '-',
  'look',
  'like',
  'near-monopoly',
  'eBooks',
  'infrastructure-as-a-service'],
 ['MNTA', 'Over', '12.00'],
 ['OI', 'Over', '21.37'],
 ['PGNX', 'Over', '3.04'],
 ['AAP',
  '-',
  'user',
  'current',
  'downtrend',
  'break',
  '.',
  'Otherwise',
  'short-term',
  'correction',
  'med-term',
  'downtrend',
  '.'],
 ['Monday',
  "'s",
  'relative',
  'weakness',
  '.',
  'NYX',
  'WIN',
  'TIE',
  'TAP',
  'ICE',
  'INT',
  'BMC',
  'AON',
  'C',
  'CHK',
  'BIIB'],
 ['GOOG',
  '-',
  'ower',
  'trend',
  'line',
  'channel',
  'test',
  '&',
  'volume',
  'support',
  '.'],
 ['AAP', 'watc

In [103]:
stem_vec=[' '.join(message) for message in stemedata]

In [104]:
stem_vec

['kicker watchlist xide tit soq pnk cpw bpz aj trade method 1 method 2 , see prev post',
 'user : aap movi . 55 % return fea/ge indic 15 trade year . awesom .',
 "user i 'd afraid short amzn - look like near-monopoli ebook infrastructure-as-a-servic",
 'mnta over 12.00',
 'oi over 21.37',
 'pgnx over 3.04',
 'aap - user current downtrend break . otherwis short-term correct med-term downtrend .',
 "monday 's rel weak . nyx win tie tap ice int bmc aon c chk biib",
 'goog - ower trend line channel test & volum support .',
 'aap watch tomorrow ong entri .',
 "'m assum fcx open tomorrow 34.25 trigger buy . still much like setup .",
 'it realli worri everyon expect market ralli , usual exact opposit happen everi time shall see soon bac spx jpm',
 "aap gamco 's arri haverti : appl is extrem cheap great video ! ! !",
 'user maykiljil post . i agre msft go higher & possibl north 30',
 'momentum come back etfc broke ma200 resist solid volum friday . ong set-up',
 'ha hit 35.65 mean resum target 

In [105]:
#applying count vectorization
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [123]:
x=cv.fit(stem_vec)

In [128]:
import pickle
with open("vectorizer.pickle","wb") as mdl_file:
    pickle.dump(x,mdl_file)

    

In [107]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5791, 8180))

In [108]:
y = df['Sentiment']

In [109]:
#importing multinomialnb from sklearn(naive_bayes)
from sklearn.naive_bayes import MultinomialNB

In [110]:
mb=MultinomialNB()

In [111]:
mb.fit(x,y)

MultinomialNB()

In [126]:
import pickle
with open("model.pickle","wb") as mdl_file:
    pickle.dump(mb,mdl_file)

In [112]:
df['Text'][3]

'MNTA Over 12.00  '

In [113]:
x[3]

array([1, 0, 0, ..., 0, 0, 0], shape=(8180,))

In [114]:
mb.predict([x[2]])

array([1])

In [115]:
[mb.predict([x[i]]) for i in range(len(x))]

[array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 arra

In [116]:
# Define the mapping
label_map = {1: 'positive', -1: 'negative', 0: 'neutral'} 



In [117]:

X_test = cv.transform(df)  # Convert text to numerical features
predicted_nums = mb.predict(X_test)  # Make predictions
predicted_labels = [label_map[num] for num in predicted_nums]  # Convert to labels

print(predicted_labels)


['negative', 'positive']


In [118]:
predicted_num = mb.predict([x[3]])[0]  # Extract the scalar value

# Convert to text label
predicted_label = label_map[predicted_num]

print(predicted_label)  

positive


In [119]:
for row in x:
    predicted_num = mb.predict([row])[0]  # Predict using the entire row
    predicted_label = label_map[predicted_num]
    print(predicted_label)


positive
positive
positive
positive
positive
positive
negative
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
negative
positive
positive
positive
positive
negative
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
negative
positive
positive
positive
positive
negative
positive
p

In [120]:
mb.score(x,y)

0.869797962355379

In [121]:

z=mb.predict(x)
pd.Series(z).value_counts()

 1    3921
-1    1870
Name: count, dtype: int64